### ISSUE TITLE
Errors are not shown in survey form

### ISSUE THREAD

**Issue by beagleknight** [HospitaletDeLlobregat/decidim-hospitalet#107]
#### :tophat: User Story

As a admin I cannot see why I cannot create a survey.

#### :clipboard: Related documentation

![image](https://cloud.githubusercontent.com/assets/106021/22687613/20bf8a96-ed29-11e6-97a9-2e9b1d65b242.png)

#### :dart: Acceptance criteria

I see the errors in survey form.

#### :pushpin: Related issues
None

**Comment by beagleknight** [comment]
After reviewing the issue with @mrcasals it's not that simple (insert boromir meme here). We need to modify the decidim `FormBuilder` and override the `collection_check_boxes` method. // cc @oriolgual

**Comment by oriolgual** [comment]
We should probably also use `decidim_form_for` instead of `form_for`
