### ISSUE TITLE
Add seeds

### ISSUE THREAD

**Issue by oriolgual** [HospitaletDeLlobregat/decidim-hospitalet#11]
#### :tophat: User Story

We need to seed the application with correct scopes and categories.

**Scopes:**

El Centre
Sant Josep
Sanfeliu
Collblanc
La Torrassa
Santa Eulàlia
Granvia
La Florida
Les Planes
Pubilla Cases
Can Serra
Bellvitge
El Gornal

**Categories**

Urbanisme i espai públic: estat dels carrers, parcs, places, etc.
Activitat econòmica i ocupació: activitat comercial, promoció econòmica, noves activitats econòmiques, etc.
Transport públic
Equipaments i serveis públics: biblioteques, centres culturals, centres esportius, serveis socials, etc.
Neteja
Activitats d’oci, culturals i de lleure
Habitatge
Educació i formació
Convivència i civisme
Medi ambient i sostenibilitat
Sanitat i salut

#### :dart: Acceptance criteria

The scopes are set for the Hospitalet organization and the main process has the categories.

**Comment by mrcasals** [comment]
Decidim seeds only run in production if [an environment variable is set](https://github.com/AjuntamentdeBarcelona/decidim/blob/f8150719f06ed1087a501d5b542ab6e385b0d9a1/decidim-core/db/seeds.rb#L2). This could cause problems when having multiple organization, so we need to check if the Decidim seeds have run.

I'd modify the app seeds file and check if there is any organization. If there is, then it means seeds were run for development mode and we don't do anything. If there isn't, then I'd create the correct organization, an admin user, a participatory process and the copes and categories listed above.

What do you think, @oriolgual @josepjaume ?

**Comment by oriolgual** [comment]
Makes sense @mrcasals, although we should have a way tu run them at production from the console or something.
