### ISSUE TITLE
Set default value (preselected value) for drop down list

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#118]
#### :tophat: User Story
As an admin, in order to optimize form submission I want to have the city of Hospitalet as a preselected value in the drop down list "A quin municipi vius?":

![imagen](https://cloud.githubusercontent.com/assets/23509895/22925197/15bc18f6-f2a8-11e6-9a4b-9bf64e4f539b.png)

#### :dart: Acceptance criteria
As an admin, I find the city of Hospitalet as a preselected value in the drop down list "A quin municipi vius?"

**Comment by mrcasals** [comment]
@carolromero should we do this also for the public part, or just the admin?

**Comment by carolromero** [comment]
@mrcasals yes! it would be great to have it for the public part as well.
