### ISSUE TITLE
Scope is not available

### ISSUE THREAD

**Issue by mrcasals** [HospitaletDeLlobregat/decidim-hospitalet#123]
#### :tophat: User Story
We got an error on Sentry about the scope not being available when creating a SurveyResult for the public page:

https://sentry.io/app60490306herokucom/decidim-hospitalet-production/issues/220388833/
https://www.lhon-participa.cat/processes/3/f/6/survey_results

Looks like a random error, so we need to investigate further.

#### :clipboard: Related documentation
None

#### :dart: Acceptance criteria
Error does not appear again

#### :pushpin: Related issues
None

**Comment by Dor3nz** [comment]
This seems pretty isolated, all events are from the same user/device. Also, can't reproduce localy, so I'm leaving this for now.
