### ISSUE TITLE
Proposals where the author didn't complete the invitation are nameless

### ISSUE THREAD

**Issue by lastpotion** [HospitaletDeLlobregat/decidim-hospitalet#129]
## :tophat: This is a bug report
At the moment when a user completes a survey correctly, if he/she doesn't accept the invitation email and completes the requested data, the proposal created it's not displaying any author name at all.

#### :clipboard: Related documentation
![screen shot 2017-02-23 at 15 42 49](https://cloud.githubusercontent.com/assets/953911/23264832/0cebe4d0-f9e3-11e6-8ee5-018392f9b129.png)
----
![screen shot 2017-02-23 at 15 42 35](https://cloud.githubusercontent.com/assets/953911/23264833/0d02920c-f9e3-11e6-8384-0e8007726c09.png)

#### :dart: Acceptance criteria
Proposals must have a way to display an author name even when the user is not registered? Maybe use ```Anonymous``` on this case?

#### :pushpin: Related issues
Related to #124

**Comment by lastpotion** [comment]
Thoughts @HospitaletDeLlobregat/developers ?

**Comment by oriolgual** [comment]
I'd displayed it yes @lastpotion even if they don't accept the invitation.

**Comment by josepjaume** [comment]
Are you sure about this @oriolgual? Wouldn't this be a privacy issue? Do authors know her name will be published when filling out the issue?

**Comment by oriolgual** [comment]
@lastpotion @josepjaume when author fill out the offline survey they accept this!
