### ISSUE TITLE
Import offline surveys

### ISSUE THREAD

**Issue by oriolgual** [HospitaletDeLlobregat/decidim-hospitalet#14]
#### :tophat: User Story

The surveys will also be available in the offline world but we need to add an interface so admin users can import these offline surveys.

The data to import is the same as in the online surveys and:

- An email
- Up to 4 proposals

We still need confirmation of this, but we'll go with a single form that submits the survey as well as the extra data.

When submitting the form we'll:

1. Create and invite a user with the given email. We'll need to use a special invitation email text explaining why the user has received the email.
2. Create a Survey result with the data from the form and assign it to the user.
3. Create each proposal (assign the scope of the proposal to the same scope chosen in the survey) and assign it to the user.

If a user with the same email exists we won't allow the submission.

#### :clipboard: Related documentation

Offline survey: https://drive.google.com/file/d/0B2voJ3vHaOfJY0tCUFlreTl4RHM/view

#### :dart: Acceptance criteria

Admins and process admins can submit offline surveys.

#### :pushpin: Related issues

- #13

**Comment by carolromero** [comment]
@oriolgual confirmed that we'll invite and create new users when submitting offline surveys.
If the email data is missing the submission will remain anonymous.

But regarding surveys submissions, we should be able to distinguish if the responses were introduced by an admin or by a registered user.

**Comment by mrcasals** [comment]
@oriolgual @carolromero we should NOT add a way to list/show survey results, right? So, once you visit the admin, you'll see directly the new survey form and, once you submit it, a message saying that everything was OK.

Is that OK?

**Comment by mrcasals** [comment]
@carolromero discussing it with @oriolgual, in the admin section we were thinking about only showing the surveys created by the admin. Is that OK with you?

**Comment by carolromero** [comment]
@mrcasals @oriolgual If it's possible, it would be better to show all responses. And also we should be able to download a csv file once the survey is closed.

**Comment by mrcasals** [comment]
@carolromero do we need to edit & delete survey submissions from the admin?

**Comment by carolromero** [comment]
@mrcasals yes, we should have that option in case we need it.
