### ISSUE TITLE
Do not validate scope if a user is not present

### ISSUE THREAD

**Issue by mrcasals** [HospitaletDeLlobregat/decidim-hospitalet#141]
#### :tophat: User Story
Do not check for scope uniqueness when no user is present.

https://github.com/HospitaletDeLlobregat/decidim-hospitalet/blob/be9d0ac331e5819129f801c1aa84a3b3968140bf/engines/decidim_hospitalet-surveys/app/models/decidim_hospitalet/surveys/survey_result.rb#L26

This validation should only be applied if a user is present.

#### :clipboard: Related documentation
None

#### :dart: Acceptance criteria
Anonymous surveys can be created properly.

#### :pushpin: Related issues
None

**Comment by oriolgual** [comment]
This allows admins to import surveys an should fix https://sentry.io/app60490306herokucom/decidim-hospitalet-production/issues/235129669/
