### ISSUE TITLE
Replies to comments order display

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#15]
#### :tophat: User Story
Responses to comments are being sorted by most recent, which causes readability issues.

![imagen](https://cloud.githubusercontent.com/assets/23509895/21716381/7f097aa4-d40a-11e6-92f4-7f21c6cf217c.png)

#### :dart: Acceptance criteria
Replies to comments are threaded chronologically

**Comment by mrcasals** [comment]
Closed in decidim by https://github.com/AjuntamentdeBarcelona/decidim/pull/464, will be added once we merge #13

**Comment by mrcasals** [comment]
Closing this since #16 is already merged.
