### ISSUE TITLE
Add TravisCI

### ISSUE THREAD

**Issue by oriolgual** [HospitaletDeLlobregat/decidim-hospitalet#3]
#### :tophat: User Story

We need a CI system to run all the tests and make sure everything is working OK.

#### :clipboard: Related documentation

https://docs.travis-ci.com/user/languages/ruby/

#### :dart: Acceptance criteria

The test suite is running at TravisCI and it's green

**Comment by mrcasals** [comment]
Travis has been added:

https://travis-ci.org/HospitaletDeLlobregat/decidim-hospitalet
