### ISSUE TITLE
Add metrics

### ISSUE THREAD

**Issue by oriolgual** [HospitaletDeLlobregat/decidim-hospitalet#4]
#### :tophat: User Story

We need to add autoamted metrics to the repo to maintain its quality over time.

#### :clipboard: Subtasks
- [ ] CodeClimate
- [x] HoundCI
- [ ] Codecov

**Comment by mrcasals** [comment]
We need admin access tot he organization in order to do so @oriolgual

**Comment by oriolgual** [comment]
Done

**Comment by mrcasals** [comment]
Adding CodeClimate at #26. Looks like I cannot add HoundCI, I don't know why, but the repo does not appear in my list of available repos :/

**Comment by oriolgual** [comment]
@mrcasals I enabled HoundCI for the organization, it should work now.

**Comment by beagleknight** [comment]
I was trying to enable codecov but I think it's restricted to organization admins :(
