### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by oriolgual** [HospitaletDeLlobregat/decidim-hospitalet#5]
#### :tophat: User Story

The current README is the default one and doesn't give and valuable information. We should update it.

#### :dart: Acceptance criteria

The README has enough information to understand this application and how to set it up for development.

**Comment by mrcasals** [comment]
Should we add information on how to install and boot the app? @oriolgual @josepjaume

**Comment by oriolgual** [comment]
Yup @mrcasals, we could also have a contribution guide and code of conduct like in Barcelona https://github.com/AjuntamentdeBarcelona/decidim-barcelon

**Comment by josepjaume** [comment]
Should these contribution guides be included as templates in decidim's app generator?

**Comment by josepjaume** [comment]
maybe optionally
