### ISSUE TITLE
Survey - Answer options for a question have changed

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#52]
#### :tophat: User Story
The answer options for the "Neighbourhood Priorities" question have changed, and now it's showing the general categories values.

#### :clipboard: Related documentation
Correct values here (Prioritats del meu barri):
https://docs.google.com/document/d/19enaJK750wC8VIijhoc9tsdJX32fCdNp1_EpGY0X-K0/edit?usp=sharing

**Comment by oriolgual** [comment]
@carolromero we were actually using the categories to load the values for this question, are the categories & neighbourhood priorities different?

**Comment by carolromero** [comment]
@oriolgual I had another set of values for categories, but I've double-checked with the council and you're right, they are the same for this process.
Sorry for the inconvenience!
