### ISSUE TITLE
Proposals after sending the survey

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#53]
#### :tophat: User Story

After submitting the survey, users should be encouraged to send a proposal.

#### :dart: Acceptance criteria
An invitation to make a new proposal (via button or link) is displayed after sending the survey.

**Comment by oriolgual** [comment]
![](https://i.imgur.com/N0Mi0GU.png)

This message will only be shown if you have sent one or more surveys.

**Comment by carolromero** [comment]
nice!
