### ISSUE TITLE
Process Home Sidebar

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#54]
#### :tophat: User Story
On the participatory process homepage there is a sidebar to the right with some data like Scope, Finish Date, Area, etc. that is missing.

#### :clipboard: Related documentation
https://decidim-design.herokuapp.com/info/

**Comment by oriolgual** [comment]
Will be fixed here: https://github.com/AjuntamentdeBarcelona/decidim/issues/620

**Comment by mrcasals** [comment]
This has already been solved, see http://decidim-hospitalet.herokuapp.com/participatory_processes/3?locale=ca for an example.
