### ISSUE TITLE
Scope list is incomplete in the survey

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#56]
#### :tophat: User Story
The full list of Scope items is not listed in the first question of the survey:
http://decidim-hospitalet.herokuapp.com/participatory_processes/3/features/6/survey_results/new

#### :dart: Acceptance criteria
All Scope list items are visible in the drop-down list

**Comment by mrcasals** [comment]
@carolromero in order to not have repeated survey results, when a user has sent a survey for a specific scope, then this scope won't appear in the list of scopes anymore. Is this the issue you are encountering?

**Comment by carolromero** [comment]
@mrcasals I see. Indeed this was the case, so I'm closing the issue.
