### ISSUE TITLE
Fix Devise email sender

### ISSUE THREAD

**Issue by oriolgual** [HospitaletDeLlobregat/decidim-hospitalet#8]
#### :tophat: User Story

All emails are sent from `info@codegram.com`, we should use an email from the Ajuntament.

#### :dart: Acceptance criteria

No emails are sent from `info@codegram.com`

**Comment by mrcasals** [comment]
@carolromero do we have any update regarding this?

**Comment by carolromero** [comment]
@mrcasals sorry for the delay. The email account is this: lhonplataforma@l-h.cat

**Comment by mrcasals** [comment]
Done!
