### ISSUE TITLE
Fix invitation email subject

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#85]
#### :tophat: User Story
When a user gets the invitation email the subject is:
"translation missing: ca.devise.mailer.invite_user.subject" and it should be:
"Confirmació inscripció L'HON-Participa"

**Comment by mrcasals** [comment]
@carolromero just to confirm, I'll translate the subject into Spanish as "Confirmación inscripción L'HON-Participa", is that OK with you?

**Comment by mrcasals** [comment]
I've merged the PR with the changes with "Confirmación inscripción L'HON-Participa" as title in Spanish. I'll open a new PR in case we need to change it.
