### ISSUE TITLE
Email invitation url doesn't get the correct layout

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#86]
#### :tophat: User Story
When a user gets an invitation email and clicks on the invitation link it shows like this:
https://decidim-hospitalet.herokuapp.com/users/invitation/accept?invitation_token=5xXsxeXQJy-KxjEa7t17&invite_redirect=%2F

#### :dart: Acceptance criteria
Invitation url shows with the correct layout

**Comment by mrcasals** [comment]
For documentation purposes, it looks like this: ![](https://i.imgur.com/ijb8WY1.png)

No errors in the JS console or missing stylesheets are found.
