### ISSUE TITLE
Add social media links to footer

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#94]
#### :tophat: User Story
Social media links are missing in the footer
![imagen](https://cloud.githubusercontent.com/assets/23509895/22584077/beed32e0-e9f0-11e6-8537-7ada05d819b4.png)

**Comment by mrcasals** [comment]
Moved to `decidim` for better discussion: https://github.com/AjuntamentdeBarcelona/decidim/issues/769

**Comment by beagleknight** [comment]
This has been merged: https://github.com/AjuntamentdeBarcelona/decidim/pull/837 We need to update `decidim` and we are done 😄

**Comment by mrcasals** [comment]
Closed by 1c775cc1ae22ef72fa4340eb06388c57db8975a7.
