### ISSUE TITLE
Missing heading styles in text editor

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#95]
#### :tophat: User Story
When creating a static page content, there are no options to apply header styles.

In Barcelona "Condicions generals" page looks like this:
![imagen](https://cloud.githubusercontent.com/assets/23509895/22584651/cc4fc2e2-e9f3-11e6-8b32-cfd36957c54b.png)

But in Hospitalet looks like this:
![imagen](https://cloud.githubusercontent.com/assets/23509895/22584663/def4db26-e9f3-11e6-9b45-ecd5065f4bdc.png)

#### :dart: Acceptance criteria
The admin can apply header styles from text editor

**Comment by mrcasals** [comment]
This issue was moved to AjuntamentdeBarcelona/decidim#760
