### ISSUE TITLE
Add Scopes to Proposals filter sidebar

### ISSUE THREAD

**Issue by carolromero** [HospitaletDeLlobregat/decidim-hospitalet#96]
#### :tophat: User Story
As a user, when I want to review the existing proposals, I should be able to filter them by scope. Since the participatory process is designed around the neighbourhoods it's important to include them as a search option.

Besides, the filters of origin and state don't apply for this process, so ideally they shouldn't be visible to avoid confusion.

![imagen](https://cloud.githubusercontent.com/assets/23509895/22637609/1a842b78-ec43-11e6-9df7-8cbd6ad7bfea.png)

#### :dart: Acceptance criteria
When reviewing Proposals, filter sidebar options are Scopes and Category.

**Comment by mrcasals** [comment]
This is being worked on in https://github.com/AjuntamentdeBarcelona/decidim/pull/778

**Comment by mrcasals** [comment]
This is already fixed at `decidim`, we will update the dependency here today so we can close this issue later :)

**Comment by carolromero** [comment]
Great @mrcasals, thanks :)
Do you think it's possible also to hide unwanted filters for a given process?

**Comment by mrcasals** [comment]
Can be done, but not from the admin right now. If you need to be able to do so from the admin, then we can open an issue at `decidim` and discuss it there.

/cc @oriolgual

**Comment by oriolgual** [comment]
I guess we could add some options to the feature to enable/disable which filters we want /cc @josepjaume

**Comment by josepjaume** [comment]
@oriolgual you're right, we should evaluate the use cases before to see if there's better abstractions for that.

**Comment by carolromero** [comment]
Maybe we can open a new issue to discuss it as @mrcasals said, but meanwhile I need a quick fix to hide state and origin filters.

**Comment by josepjaume** [comment]
Instead of just putting flags to enable or dissble filters, let's abstract
this into a "Enable official proposals" which activates both the feature
and the filters.

**Comment by mrcasals** [comment]
@josepjaume I don't understand how this will fix the issue :/

**Comment by oriolgual** [comment]
As explained in Slack: instead of adding settings to enable or disable filters, we add setting to enable  features, in this case:

- Enable official proposals: This will add a filter to the index & allow creating proposals from the admin
- Enable proposal answering: This will add a filter to the index & allow answering a proposal from the admin

We should move this to Decidim.

**Comment by oriolgual** [comment]
Closed by #113
